/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMdiArea>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>
#include "duoconfigwidget.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QWidget *verticalLayoutWidget;
    QVBoxLayout *verticalLayout;
    QTabWidget *tabWidget;
    QWidget *tab;
    QFrame *line;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QFrame *line_2;
    QLabel *label_4;
    QRadioButton *radioButton;
    QRadioButton *radioButton_2;
    QRadioButton *radioButton_3;
    QRadioButton *radioButton_4;
    QLabel *label_5;
    QComboBox *deviceComboBox;
    QFrame *line_3;
    QGroupBox *groupBox;
    QSlider *horizontalSlider;
    QLabel *label_9;
    QCheckBox *checkBox;
    QLabel *label_13;
    QSlider *horizontalSlider_3;
    QLabel *label_14;
    QLabel *label_15;
    QCheckBox *checkBox_3;
    QCheckBox *checkBox_4;
    QCheckBox *checkBox_5;
    QSlider *horizontalSlider_4;
    QSlider *horizontalSlider_5;
    QLabel *label_20;
    QSlider *horizontalSlider_6;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QLCDNumber *lcdPeakCPU0;
    QLCDNumber *lcdPeakCPU1;
    QLCDNumber *lcdPeakCPU2;
    QLCDNumber *lcdPeakCPU3;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLCDNumber *lcdPeakGPU;
    QLabel *label_28;
    QPushButton *pushButton_4;
    QPushButton *calibratorBtn;
    QLabel *label_10;
    QGroupBox *groupBox_2;
    QMdiArea *mdiArea;
    QProgressBar *progressBar;
    QLabel *label_16;
    QMdiArea *mdiArea_2;
    QMdiArea *mdiArea_4;
    QMdiArea *mdiArea_3;
    QMdiArea *mdiArea_5;
    QLabel *label_11;
    QFrame *line_4;
    QLabel *label_12;
    QFrame *line_5;
    QFrame *line_6;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QPushButton *pushButton_3;
    QProgressBar *progressBar_2;
    QLabel *label_29;
    DUOConfigWidget *deviceConfigurationWidget;
    QFrame *frame;
    QLabel *label_6;
    QLabel *label_8;
    QComboBox *inputFrameTypeComboBox;
    QLineEdit *frameHeightEdit;
    QLabel *label_7;
    QLineEdit *frameWidthEdit;
    QLabel *label_56;
    QComboBox *outputFrameTypeComboBox;
    QFrame *line_7;
    QComboBox *processingModeComboBox;
    QLabel *label_33;
    QPushButton *recordToBtn;
    QWidget *tab_2;
    QFrame *frame_2;
    QLabel *label_34;
    QLabel *label_35;
    QFrame *line_9;
    QSpinBox *spinBox;
    QLabel *label_36;
    QSpinBox *spinBox_2;
    QLabel *label_37;
    QSpinBox *spinBox_3;
    QSpinBox *spinBox_4;
    QLabel *label_38;
    QLabel *label_39;
    QSlider *horizontalSlider_2;
    QLCDNumber *lcdTargetObjectEccentricty;
    QLabel *label_40;
    QSpinBox *spinBox_5;
    QLabel *label_41;
    QSpinBox *spinBox_6;
    QLabel *label_42;
    QLabel *label_43;
    QSpinBox *spinBox_7;
    QLabel *label_44;
    QLabel *label_45;
    QSpinBox *spinBox_8;
    QLabel *label_46;
    QDoubleSpinBox *doubleSpinBox;
    QLabel *label_47;
    QSpinBox *spinBox_9;
    QLabel *label_48;
    QDoubleSpinBox *doubleSpinBox_2;
    QLabel *label_49;
    QLabel *label_50;
    QFrame *line_10;
    QLCDNumber *lcdTargetObjectEccentricty_2;
    QSlider *horizontalSlider_7;
    QLCDNumber *lcdTargetObjectEccentricty_3;
    QSlider *horizontalSlider_8;
    QFrame *frame_3;
    QLabel *label_51;
    QDoubleSpinBox *doubleSpinBox_3;
    QLabel *label_52;
    QLabel *label_53;
    QDoubleSpinBox *doubleSpinBox_4;
    QDoubleSpinBox *doubleSpinBox_5;
    QLabel *label_54;
    QSpinBox *spinBox_10;
    QFrame *line_11;
    QLabel *label_55;
    QSpinBox *spinBox_11;
    QLabel *label_30;
    QLabel *label_31;
    QRadioButton *radioButton_5;
    QRadioButton *radioButton_6;
    QLabel *label_32;
    QWidget *tab_4;
    QWidget *tab_5;
    QWidget *tab_3;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuView;
    QMenu *menuHelp;
    QStatusBar *statusBar;
    QButtonGroup *buttonGroup;
    QButtonGroup *buttonGroup_2;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(986, 567);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        verticalLayoutWidget = new QWidget(centralWidget);
        verticalLayoutWidget->setObjectName(QStringLiteral("verticalLayoutWidget"));
        verticalLayoutWidget->setGeometry(QRect(-1, -1, 921, 511));
        verticalLayout = new QVBoxLayout(verticalLayoutWidget);
        verticalLayout->setSpacing(6);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        tabWidget = new QTabWidget(verticalLayoutWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        line = new QFrame(tab);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(0, 240, 921, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        label = new QLabel(tab);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 0, 111, 16));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        label->setFont(font);
        label_2 = new QLabel(tab);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 230, 131, 16));
        label_2->setFont(font);
        label_3 = new QLabel(tab);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 30, 111, 16));
        line_2 = new QFrame(tab);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(0, 10, 921, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        label_4 = new QLabel(tab);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 50, 101, 16));
        radioButton = new QRadioButton(tab);
        buttonGroup = new QButtonGroup(MainWindow);
        buttonGroup->setObjectName(QStringLiteral("buttonGroup"));
        buttonGroup->addButton(radioButton);
        radioButton->setObjectName(QStringLiteral("radioButton"));
        radioButton->setGeometry(QRect(130, 30, 91, 20));
        radioButton_2 = new QRadioButton(tab);
        buttonGroup->addButton(radioButton_2);
        radioButton_2->setObjectName(QStringLiteral("radioButton_2"));
        radioButton_2->setGeometry(QRect(230, 30, 81, 20));
        radioButton_3 = new QRadioButton(tab);
        buttonGroup_2 = new QButtonGroup(MainWindow);
        buttonGroup_2->setObjectName(QStringLiteral("buttonGroup_2"));
        buttonGroup_2->addButton(radioButton_3);
        radioButton_3->setObjectName(QStringLiteral("radioButton_3"));
        radioButton_3->setGeometry(QRect(130, 50, 91, 20));
        radioButton_4 = new QRadioButton(tab);
        buttonGroup_2->addButton(radioButton_4);
        radioButton_4->setObjectName(QStringLiteral("radioButton_4"));
        radioButton_4->setGeometry(QRect(230, 50, 91, 20));
        label_5 = new QLabel(tab);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 80, 101, 16));
        deviceComboBox = new QComboBox(tab);
        deviceComboBox->setObjectName(QStringLiteral("deviceComboBox"));
        deviceComboBox->setGeometry(QRect(130, 70, 181, 25));
        line_3 = new QFrame(tab);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(460, 20, 20, 225));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        groupBox = new QGroupBox(tab);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 260, 461, 211));
        groupBox->setAutoFillBackground(false);
        groupBox->setStyleSheet(QStringLiteral(""));
        groupBox->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        horizontalSlider = new QSlider(groupBox);
        horizontalSlider->setObjectName(QStringLiteral("horizontalSlider"));
        horizontalSlider->setGeometry(QRect(180, 20, 141, 19));
        horizontalSlider->setMaximum(19);
        horizontalSlider->setOrientation(Qt::Horizontal);
        horizontalSlider->setTickPosition(QSlider::NoTicks);
        label_9 = new QLabel(groupBox);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(0, 20, 81, 16));
        checkBox = new QCheckBox(groupBox);
        checkBox->setObjectName(QStringLiteral("checkBox"));
        checkBox->setGeometry(QRect(100, 20, 71, 20));
        label_13 = new QLabel(groupBox);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(0, 40, 81, 16));
        horizontalSlider_3 = new QSlider(groupBox);
        horizontalSlider_3->setObjectName(QStringLiteral("horizontalSlider_3"));
        horizontalSlider_3->setGeometry(QRect(180, 40, 141, 20));
        horizontalSlider_3->setMaximum(19);
        horizontalSlider_3->setOrientation(Qt::Horizontal);
        horizontalSlider_3->setTickPosition(QSlider::NoTicks);
        label_14 = new QLabel(groupBox);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(0, 60, 81, 16));
        label_15 = new QLabel(groupBox);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(0, 80, 81, 16));
        checkBox_3 = new QCheckBox(groupBox);
        checkBox_3->setObjectName(QStringLiteral("checkBox_3"));
        checkBox_3->setGeometry(QRect(100, 40, 71, 20));
        checkBox_4 = new QCheckBox(groupBox);
        checkBox_4->setObjectName(QStringLiteral("checkBox_4"));
        checkBox_4->setGeometry(QRect(100, 60, 71, 20));
        checkBox_5 = new QCheckBox(groupBox);
        checkBox_5->setObjectName(QStringLiteral("checkBox_5"));
        checkBox_5->setGeometry(QRect(100, 80, 71, 20));
        horizontalSlider_4 = new QSlider(groupBox);
        horizontalSlider_4->setObjectName(QStringLiteral("horizontalSlider_4"));
        horizontalSlider_4->setGeometry(QRect(180, 60, 141, 20));
        horizontalSlider_4->setMaximum(19);
        horizontalSlider_4->setOrientation(Qt::Horizontal);
        horizontalSlider_5 = new QSlider(groupBox);
        horizontalSlider_5->setObjectName(QStringLiteral("horizontalSlider_5"));
        horizontalSlider_5->setGeometry(QRect(180, 80, 141, 20));
        horizontalSlider_5->setMaximum(19);
        horizontalSlider_5->setOrientation(Qt::Horizontal);
        label_20 = new QLabel(groupBox);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(0, 120, 41, 16));
        horizontalSlider_6 = new QSlider(groupBox);
        horizontalSlider_6->setObjectName(QStringLiteral("horizontalSlider_6"));
        horizontalSlider_6->setGeometry(QRect(180, 120, 141, 19));
        horizontalSlider_6->setMaximum(14);
        horizontalSlider_6->setOrientation(Qt::Horizontal);
        pushButton = new QPushButton(groupBox);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(0, 184, 151, 27));
        pushButton_2 = new QPushButton(groupBox);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(0, 156, 151, 27));
        lcdPeakCPU0 = new QLCDNumber(groupBox);
        lcdPeakCPU0->setObjectName(QStringLiteral("lcdPeakCPU0"));
        lcdPeakCPU0->setEnabled(true);
        lcdPeakCPU0->setGeometry(QRect(340, 19, 51, 18));
        lcdPeakCPU1 = new QLCDNumber(groupBox);
        lcdPeakCPU1->setObjectName(QStringLiteral("lcdPeakCPU1"));
        lcdPeakCPU1->setGeometry(QRect(340, 40, 51, 18));
        lcdPeakCPU2 = new QLCDNumber(groupBox);
        lcdPeakCPU2->setObjectName(QStringLiteral("lcdPeakCPU2"));
        lcdPeakCPU2->setGeometry(QRect(340, 61, 51, 18));
        lcdPeakCPU3 = new QLCDNumber(groupBox);
        lcdPeakCPU3->setObjectName(QStringLiteral("lcdPeakCPU3"));
        lcdPeakCPU3->setGeometry(QRect(340, 82, 51, 18));
        label_24 = new QLabel(groupBox);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(400, 19, 51, 16));
        label_25 = new QLabel(groupBox);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(400, 40, 51, 16));
        label_26 = new QLabel(groupBox);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(400, 61, 51, 16));
        label_27 = new QLabel(groupBox);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(400, 82, 51, 16));
        lcdPeakGPU = new QLCDNumber(groupBox);
        lcdPeakGPU->setObjectName(QStringLiteral("lcdPeakGPU"));
        lcdPeakGPU->setGeometry(QRect(340, 120, 51, 18));
        label_28 = new QLabel(groupBox);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(400, 120, 51, 16));
        pushButton_4 = new QPushButton(groupBox);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(280, 184, 151, 27));
        calibratorBtn = new QPushButton(groupBox);
        calibratorBtn->setObjectName(QStringLiteral("calibratorBtn"));
        calibratorBtn->setGeometry(QRect(280, 157, 151, 27));
        label_10 = new QLabel(tab);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 252, 131, 16));
        QFont font1;
        font1.setBold(false);
        font1.setWeight(50);
        label_10->setFont(font1);
        label_10->setAutoFillBackground(true);
        groupBox_2 = new QGroupBox(tab);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(480, 260, 461, 211));
        groupBox_2->setStyleSheet(QStringLiteral(""));
        groupBox_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        mdiArea = new QMdiArea(groupBox_2);
        mdiArea->setObjectName(QStringLiteral("mdiArea"));
        mdiArea->setGeometry(QRect(0, 21, 95, 95));
        mdiArea->setAutoFillBackground(true);
        QBrush brush(QColor(237, 236, 235, 255));
        brush.setStyle(Qt::NoBrush);
        mdiArea->setBackground(brush);
        progressBar = new QProgressBar(groupBox_2);
        progressBar->setObjectName(QStringLiteral("progressBar"));
        progressBar->setGeometry(QRect(300, 178, 121, 31));
        progressBar->setStyleSheet(QStringLiteral(""));
        progressBar->setValue(24);
        progressBar->setTextVisible(true);
        label_16 = new QLabel(groupBox_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(260, 193, 31, 16));
        label_16->setFont(font1);
        label_16->setAutoFillBackground(true);
        mdiArea_2 = new QMdiArea(groupBox_2);
        mdiArea_2->setObjectName(QStringLiteral("mdiArea_2"));
        mdiArea_2->setGeometry(QRect(94, 21, 95, 95));
        mdiArea_2->setAutoFillBackground(true);
        QBrush brush1(QColor(237, 236, 235, 255));
        brush1.setStyle(Qt::NoBrush);
        mdiArea_2->setBackground(brush1);
        mdiArea_4 = new QMdiArea(groupBox_2);
        mdiArea_4->setObjectName(QStringLiteral("mdiArea_4"));
        mdiArea_4->setGeometry(QRect(94, 115, 95, 95));
        mdiArea_4->setAutoFillBackground(true);
        QBrush brush2(QColor(237, 236, 235, 255));
        brush2.setStyle(Qt::NoBrush);
        mdiArea_4->setBackground(brush2);
        mdiArea_3 = new QMdiArea(groupBox_2);
        mdiArea_3->setObjectName(QStringLiteral("mdiArea_3"));
        mdiArea_3->setGeometry(QRect(0, 115, 95, 95));
        mdiArea_3->setAutoFillBackground(true);
        QBrush brush3(QColor(237, 236, 235, 255));
        brush3.setStyle(Qt::NoBrush);
        mdiArea_3->setBackground(brush3);
        mdiArea_5 = new QMdiArea(groupBox_2);
        mdiArea_5->setObjectName(QStringLiteral("mdiArea_5"));
        mdiArea_5->setGeometry(QRect(260, 20, 161, 151));
        mdiArea_5->setAutoFillBackground(true);
        QBrush brush4(QColor(237, 236, 235, 255));
        brush4.setStyle(Qt::NoBrush);
        mdiArea_5->setBackground(brush4);
        label_11 = new QLabel(tab);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(480, 252, 81, 16));
        label_11->setFont(font1);
        label_11->setAutoFillBackground(true);
        line_4 = new QFrame(tab);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(10, 360, 431, 20));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        label_12 = new QLabel(tab);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(740, 440, 31, 16));
        label_12->setFont(font1);
        label_12->setAutoFillBackground(true);
        line_5 = new QFrame(tab);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(340, 600, 421, 16));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(tab);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(10, 120, 431, 20));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        label_17 = new QLabel(tab);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(10, 140, 101, 16));
        label_18 = new QLabel(tab);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(10, 180, 121, 16));
        label_19 = new QLabel(tab);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(160, 140, 81, 16));
        label_21 = new QLabel(tab);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 160, 101, 16));
        label_22 = new QLabel(tab);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(160, 160, 121, 16));
        label_23 = new QLabel(tab);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(160, 180, 141, 16));
        pushButton_3 = new QPushButton(tab);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(350, 140, 91, 55));
        progressBar_2 = new QProgressBar(tab);
        progressBar_2->setObjectName(QStringLiteral("progressBar_2"));
        progressBar_2->setGeometry(QRect(160, 203, 281, 16));
        progressBar_2->setValue(65);
        label_29 = new QLabel(tab);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(10, 202, 121, 16));
        deviceConfigurationWidget = new DUOConfigWidget(tab);
        deviceConfigurationWidget->setObjectName(QStringLiteral("deviceConfigurationWidget"));
        deviceConfigurationWidget->setEnabled(true);
        deviceConfigurationWidget->setGeometry(QRect(479, 70, 421, 171));
        frame = new QFrame(tab);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(479, 30, 421, 31));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        label_6 = new QLabel(frame);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(4, 7, 91, 16));
        label_8 = new QLabel(frame);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(180, 7, 21, 16));
        inputFrameTypeComboBox = new QComboBox(frame);
        inputFrameTypeComboBox->setObjectName(QStringLiteral("inputFrameTypeComboBox"));
        inputFrameTypeComboBox->setGeometry(QRect(200, 3, 61, 25));
        frameHeightEdit = new QLineEdit(frame);
        frameHeightEdit->setObjectName(QStringLiteral("frameHeightEdit"));
        frameHeightEdit->setGeometry(QRect(130, 3, 41, 25));
        label_7 = new QLabel(frame);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(120, 7, 16, 16));
        frameWidthEdit = new QLineEdit(frame);
        frameWidthEdit->setObjectName(QStringLiteral("frameWidthEdit"));
        frameWidthEdit->setGeometry(QRect(77, 3, 41, 25));
        label_56 = new QLabel(frame);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(270, 7, 41, 16));
        outputFrameTypeComboBox = new QComboBox(frame);
        outputFrameTypeComboBox->setObjectName(QStringLiteral("outputFrameTypeComboBox"));
        outputFrameTypeComboBox->setGeometry(QRect(300, 3, 111, 25));
        line_7 = new QFrame(tab);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(10, 400, 431, 20));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        processingModeComboBox = new QComboBox(tab);
        processingModeComboBox->setObjectName(QStringLiteral("processingModeComboBox"));
        processingModeComboBox->setGeometry(QRect(130, 100, 181, 25));
        label_33 = new QLabel(tab);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(10, 103, 121, 16));
        recordToBtn = new QPushButton(tab);
        recordToBtn->setObjectName(QStringLiteral("recordToBtn"));
        recordToBtn->setGeometry(QRect(321, 100, 121, 25));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        frame_2 = new QFrame(tab_2);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(10, 50, 441, 321));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        label_34 = new QLabel(frame_2);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(10, 10, 231, 20));
        label_34->setFont(font1);
        label_35 = new QLabel(frame_2);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(10, 89, 211, 20));
        label_35->setFont(font1);
        line_9 = new QFrame(frame_2);
        line_9->setObjectName(QStringLiteral("line_9"));
        line_9->setGeometry(QRect(10, 150, 421, 20));
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        spinBox = new QSpinBox(frame_2);
        spinBox->setObjectName(QStringLiteral("spinBox"));
        spinBox->setGeometry(QRect(370, 10, 48, 21));
        label_36 = new QLabel(frame_2);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(10, 30, 241, 20));
        label_36->setFont(font1);
        spinBox_2 = new QSpinBox(frame_2);
        spinBox_2->setObjectName(QStringLiteral("spinBox_2"));
        spinBox_2->setGeometry(QRect(370, 30, 48, 21));
        label_37 = new QLabel(frame_2);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(10, 69, 241, 20));
        label_37->setFont(font1);
        spinBox_3 = new QSpinBox(frame_2);
        spinBox_3->setObjectName(QStringLiteral("spinBox_3"));
        spinBox_3->setGeometry(QRect(270, 69, 48, 21));
        spinBox_4 = new QSpinBox(frame_2);
        spinBox_4->setObjectName(QStringLiteral("spinBox_4"));
        spinBox_4->setGeometry(QRect(370, 70, 48, 21));
        label_38 = new QLabel(frame_2);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(230, 70, 51, 20));
        label_38->setFont(font1);
        label_39 = new QLabel(frame_2);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(322, 70, 51, 20));
        label_39->setFont(font1);
        horizontalSlider_2 = new QSlider(frame_2);
        horizontalSlider_2->setObjectName(QStringLiteral("horizontalSlider_2"));
        horizontalSlider_2->setGeometry(QRect(229, 89, 141, 20));
        horizontalSlider_2->setMinimum(1);
        horizontalSlider_2->setMaximum(100);
        horizontalSlider_2->setOrientation(Qt::Horizontal);
        lcdTargetObjectEccentricty = new QLCDNumber(frame_2);
        lcdTargetObjectEccentricty->setObjectName(QStringLiteral("lcdTargetObjectEccentricty"));
        lcdTargetObjectEccentricty->setEnabled(true);
        lcdTargetObjectEccentricty->setGeometry(QRect(370, 91, 51, 18));
        lcdTargetObjectEccentricty->setStyleSheet(QStringLiteral("background-color: black; color: lightgreen;"));
        lcdTargetObjectEccentricty->setSegmentStyle(QLCDNumber::Flat);
        label_40 = new QLabel(frame_2);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(10, 129, 211, 20));
        label_40->setFont(font1);
        spinBox_5 = new QSpinBox(frame_2);
        spinBox_5->setObjectName(QStringLiteral("spinBox_5"));
        spinBox_5->setGeometry(QRect(370, 109, 48, 21));
        label_41 = new QLabel(frame_2);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(10, 170, 211, 20));
        label_41->setFont(font1);
        spinBox_6 = new QSpinBox(frame_2);
        spinBox_6->setObjectName(QStringLiteral("spinBox_6"));
        spinBox_6->setGeometry(QRect(370, 170, 48, 21));
        label_42 = new QLabel(frame_2);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(420, 170, 21, 20));
        label_42->setFont(font1);
        label_43 = new QLabel(frame_2);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(10, 109, 221, 20));
        label_43->setFont(font1);
        spinBox_7 = new QSpinBox(frame_2);
        spinBox_7->setObjectName(QStringLiteral("spinBox_7"));
        spinBox_7->setGeometry(QRect(370, 129, 48, 21));
        label_44 = new QLabel(frame_2);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(420, 110, 21, 20));
        label_44->setFont(font1);
        label_45 = new QLabel(frame_2);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(10, 50, 241, 20));
        label_45->setFont(font1);
        spinBox_8 = new QSpinBox(frame_2);
        spinBox_8->setObjectName(QStringLiteral("spinBox_8"));
        spinBox_8->setGeometry(QRect(370, 50, 48, 21));
        label_46 = new QLabel(frame_2);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(10, 230, 181, 20));
        label_46->setFont(font1);
        doubleSpinBox = new QDoubleSpinBox(frame_2);
        doubleSpinBox->setObjectName(QStringLiteral("doubleSpinBox"));
        doubleSpinBox->setGeometry(QRect(350, 230, 68, 21));
        label_47 = new QLabel(frame_2);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(10, 210, 181, 20));
        label_47->setFont(font1);
        spinBox_9 = new QSpinBox(frame_2);
        spinBox_9->setObjectName(QStringLiteral("spinBox_9"));
        spinBox_9->setGeometry(QRect(370, 210, 48, 21));
        label_48 = new QLabel(frame_2);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(10, 190, 221, 20));
        label_48->setFont(font1);
        doubleSpinBox_2 = new QDoubleSpinBox(frame_2);
        doubleSpinBox_2->setObjectName(QStringLiteral("doubleSpinBox_2"));
        doubleSpinBox_2->setGeometry(QRect(350, 190, 68, 21));
        label_49 = new QLabel(frame_2);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(10, 270, 241, 20));
        label_49->setFont(font1);
        label_50 = new QLabel(frame_2);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(10, 290, 241, 20));
        label_50->setFont(font1);
        line_10 = new QFrame(frame_2);
        line_10->setObjectName(QStringLiteral("line_10"));
        line_10->setGeometry(QRect(10, 250, 421, 20));
        line_10->setFrameShape(QFrame::HLine);
        line_10->setFrameShadow(QFrame::Sunken);
        lcdTargetObjectEccentricty_2 = new QLCDNumber(frame_2);
        lcdTargetObjectEccentricty_2->setObjectName(QStringLiteral("lcdTargetObjectEccentricty_2"));
        lcdTargetObjectEccentricty_2->setEnabled(true);
        lcdTargetObjectEccentricty_2->setGeometry(QRect(371, 272, 51, 18));
        lcdTargetObjectEccentricty_2->setStyleSheet(QStringLiteral("background-color: black; color: lightgreen;"));
        lcdTargetObjectEccentricty_2->setSegmentStyle(QLCDNumber::Flat);
        horizontalSlider_7 = new QSlider(frame_2);
        horizontalSlider_7->setObjectName(QStringLiteral("horizontalSlider_7"));
        horizontalSlider_7->setGeometry(QRect(230, 270, 141, 20));
        horizontalSlider_7->setMinimum(1);
        horizontalSlider_7->setMaximum(100);
        horizontalSlider_7->setOrientation(Qt::Horizontal);
        lcdTargetObjectEccentricty_3 = new QLCDNumber(frame_2);
        lcdTargetObjectEccentricty_3->setObjectName(QStringLiteral("lcdTargetObjectEccentricty_3"));
        lcdTargetObjectEccentricty_3->setEnabled(true);
        lcdTargetObjectEccentricty_3->setGeometry(QRect(371, 292, 51, 18));
        lcdTargetObjectEccentricty_3->setStyleSheet(QStringLiteral("background-color: black; color: lightgreen;"));
        lcdTargetObjectEccentricty_3->setSegmentStyle(QLCDNumber::Flat);
        horizontalSlider_8 = new QSlider(frame_2);
        horizontalSlider_8->setObjectName(QStringLiteral("horizontalSlider_8"));
        horizontalSlider_8->setGeometry(QRect(230, 290, 141, 20));
        horizontalSlider_8->setMinimum(1);
        horizontalSlider_8->setMaximum(100);
        horizontalSlider_8->setOrientation(Qt::Horizontal);
        frame_3 = new QFrame(tab_2);
        frame_3->setObjectName(QStringLiteral("frame_3"));
        frame_3->setGeometry(QRect(460, 50, 441, 321));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        label_51 = new QLabel(frame_3);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(10, 10, 241, 20));
        label_51->setFont(font1);
        doubleSpinBox_3 = new QDoubleSpinBox(frame_3);
        doubleSpinBox_3->setObjectName(QStringLiteral("doubleSpinBox_3"));
        doubleSpinBox_3->setGeometry(QRect(350, 10, 68, 21));
        label_52 = new QLabel(frame_3);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(10, 50, 261, 20));
        label_52->setFont(font1);
        label_53 = new QLabel(frame_3);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(10, 70, 261, 20));
        label_53->setFont(font1);
        doubleSpinBox_4 = new QDoubleSpinBox(frame_3);
        doubleSpinBox_4->setObjectName(QStringLiteral("doubleSpinBox_4"));
        doubleSpinBox_4->setGeometry(QRect(350, 50, 68, 21));
        doubleSpinBox_5 = new QDoubleSpinBox(frame_3);
        doubleSpinBox_5->setObjectName(QStringLiteral("doubleSpinBox_5"));
        doubleSpinBox_5->setGeometry(QRect(350, 70, 68, 21));
        label_54 = new QLabel(frame_3);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(10, 90, 321, 20));
        label_54->setFont(font1);
        spinBox_10 = new QSpinBox(frame_3);
        spinBox_10->setObjectName(QStringLiteral("spinBox_10"));
        spinBox_10->setGeometry(QRect(370, 90, 48, 21));
        line_11 = new QFrame(frame_3);
        line_11->setObjectName(QStringLiteral("line_11"));
        line_11->setGeometry(QRect(10, 30, 421, 20));
        line_11->setFrameShape(QFrame::HLine);
        line_11->setFrameShadow(QFrame::Sunken);
        label_55 = new QLabel(frame_3);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(10, 110, 281, 20));
        label_55->setFont(font1);
        spinBox_11 = new QSpinBox(frame_3);
        spinBox_11->setObjectName(QStringLiteral("spinBox_11"));
        spinBox_11->setGeometry(QRect(370, 110, 48, 21));
        label_30 = new QLabel(tab_2);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(20, 42, 131, 16));
        label_30->setAutoFillBackground(true);
        label_31 = new QLabel(tab_2);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(470, 42, 131, 16));
        label_31->setAutoFillBackground(true);
        radioButton_5 = new QRadioButton(tab_2);
        radioButton_5->setObjectName(QStringLiteral("radioButton_5"));
        radioButton_5->setGeometry(QRect(100, 10, 151, 20));
        radioButton_6 = new QRadioButton(tab_2);
        radioButton_6->setObjectName(QStringLiteral("radioButton_6"));
        radioButton_6->setGeometry(QRect(260, 10, 181, 20));
        label_32 = new QLabel(tab_2);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(10, 10, 91, 20));
        tabWidget->addTab(tab_2, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        tabWidget->addTab(tab_5, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        tabWidget->addTab(tab_3, QString());

        verticalLayout->addWidget(tabWidget);

        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 986, 23));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        menuView = new QMenu(menuBar);
        menuView->setObjectName(QStringLiteral("menuView"));
        menuHelp = new QMenu(menuBar);
        menuHelp->setObjectName(QStringLiteral("menuHelp"));
        MainWindow->setMenuBar(menuBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuView->menuAction());
        menuBar->addAction(menuHelp->menuAction());

        retranslateUi(MainWindow);
        QObject::connect(horizontalSlider_2, SIGNAL(valueChanged(int)), lcdTargetObjectEccentricty, SLOT(display(int)));
        QObject::connect(horizontalSlider_7, SIGNAL(valueChanged(int)), lcdTargetObjectEccentricty_2, SLOT(display(int)));
        QObject::connect(horizontalSlider_8, SIGNAL(valueChanged(int)), lcdTargetObjectEccentricty_3, SLOT(display(int)));

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Tracker RT", 0));
        label->setText(QApplication::translate("MainWindow", "Camera Sensors", 0));
        label_2->setText(QApplication::translate("MainWindow", "NVIDIA Jetson TK1", 0));
        label_3->setText(QApplication::translate("MainWindow", "Technology:", 0));
        label_4->setText(QApplication::translate("MainWindow", "Mode:", 0));
        radioButton->setText(QApplication::translate("MainWindow", "Camera", 0));
        radioButton_2->setText(QApplication::translate("MainWindow", "Infrared", 0));
        radioButton_3->setText(QApplication::translate("MainWindow", "Mono", 0));
        radioButton_4->setText(QApplication::translate("MainWindow", "Stereo", 0));
        label_5->setText(QApplication::translate("MainWindow", "Device:", 0));
        deviceComboBox->clear();
        deviceComboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "ZED Stereo Camera", 0)
         << QApplication::translate("MainWindow", "DUO Stereo Camera", 0)
         << QApplication::translate("MainWindow", "Kinect IR Depth Sensor", 0)
         << QApplication::translate("MainWindow", "Virtual Mono Camera", 0)
         << QApplication::translate("MainWindow", "Virtual Stereo Camera", 0)
        );
        groupBox->setTitle(QString());
        label_9->setText(QApplication::translate("MainWindow", "CPU Core 0:", 0));
        checkBox->setText(QApplication::translate("MainWindow", "Active", 0));
        label_13->setText(QApplication::translate("MainWindow", "CPU Core 1:", 0));
        label_14->setText(QApplication::translate("MainWindow", "CPU Core 2:", 0));
        label_15->setText(QApplication::translate("MainWindow", "CPU Core 3:", 0));
        checkBox_3->setText(QApplication::translate("MainWindow", "Active", 0));
        checkBox_4->setText(QApplication::translate("MainWindow", "Active", 0));
        checkBox_5->setText(QApplication::translate("MainWindow", "Active", 0));
        label_20->setText(QApplication::translate("MainWindow", "GPU:", 0));
        pushButton->setText(QApplication::translate("MainWindow", "Maximal Performance", 0));
        pushButton_2->setText(QApplication::translate("MainWindow", "Low Power", 0));
        label_24->setText(QApplication::translate("MainWindow", "[MHz]", 0));
        label_25->setText(QApplication::translate("MainWindow", "[MHz]", 0));
        label_26->setText(QApplication::translate("MainWindow", "[MHz]", 0));
        label_27->setText(QApplication::translate("MainWindow", "[MHz]", 0));
        label_28->setText(QApplication::translate("MainWindow", "[MHz]", 0));
        pushButton_4->setText(QApplication::translate("MainWindow", "Start Application", 0));
        calibratorBtn->setText(QApplication::translate("MainWindow", "Start Calibrator", 0));
        label_10->setText(QApplication::translate("MainWindow", "Performance Tuning", 0));
        groupBox_2->setTitle(QString());
        label_16->setText(QApplication::translate("MainWindow", "Mem", 0));
        label_11->setText(QApplication::translate("MainWindow", "Diagnostics", 0));
        label_12->setText(QApplication::translate("MainWindow", "GPU", 0));
        label_17->setText(QApplication::translate("MainWindow", "Device Status:", 0));
        label_18->setText(QApplication::translate("MainWindow", "Firmware/Library:", 0));
        label_19->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#32cd32;\">Online</span></p></body></html>", 0));
        label_21->setText(QApplication::translate("MainWindow", "Platform Port:", 0));
        label_22->setText(QApplication::translate("MainWindow", "USB 3.0 Controller", 0));
        label_23->setText(QApplication::translate("MainWindow", "DUO SDK v1.0.50.26", 0));
        pushButton_3->setText(QApplication::translate("MainWindow", "Test Device", 0));
        label_29->setText(QApplication::translate("MainWindow", "Device Testing:", 0));
        label_6->setText(QApplication::translate("MainWindow", "Resolution:", 0));
        label_8->setText(QApplication::translate("MainWindow", "In:", 0));
        inputFrameTypeComboBox->clear();
        inputFrameTypeComboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "Grey", 0)
         << QApplication::translate("MainWindow", "RGB", 0)
        );
        frameHeightEdit->setText(QApplication::translate("MainWindow", "800", 0));
        label_7->setText(QApplication::translate("MainWindow", "x", 0));
        frameWidthEdit->setText(QApplication::translate("MainWindow", "1280", 0));
        label_56->setText(QApplication::translate("MainWindow", "Out:", 0));
        outputFrameTypeComboBox->clear();
        outputFrameTypeComboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "Immuted", 0)
         << QApplication::translate("MainWindow", "Force RGB", 0)
        );
        processingModeComboBox->clear();
        processingModeComboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "Tracking", 0)
         << QApplication::translate("MainWindow", "Recording", 0)
        );
        label_33->setText(QApplication::translate("MainWindow", "Processing Mode:", 0));
        recordToBtn->setText(QApplication::translate("MainWindow", "Record To...", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Dashboard", 0));
        label_34->setText(QApplication::translate("MainWindow", "Morphological Dilation Kernel Size:", 0));
        label_35->setText(QApplication::translate("MainWindow", "Target Object Eccentricity EPS:", 0));
        label_36->setText(QApplication::translate("MainWindow", "Contrast-Dilate Grayscale Threshold:", 0));
        label_37->setText(QApplication::translate("MainWindow", "Target Object Minimum Size:", 0));
        label_38->setText(QApplication::translate("MainWindow", "Width:", 0));
        label_39->setText(QApplication::translate("MainWindow", "Height:", 0));
        label_40->setText(QApplication::translate("MainWindow", "Montecarlo Estimate Iterations:", 0));
        label_41->setText(QApplication::translate("MainWindow", "Flow Region Overlap Tolerance:", 0));
        label_42->setText(QApplication::translate("MainWindow", "px", 0));
        label_43->setText(QApplication::translate("MainWindow", "Target Object Overlap Tolerance:", 0));
        label_44->setText(QApplication::translate("MainWindow", "px", 0));
        label_45->setText(QApplication::translate("MainWindow", "Contrast-Dilate Retry Episodes:", 0));
        label_46->setText(QApplication::translate("MainWindow", "Trajectory Relational Factor:", 0));
        label_47->setText(QApplication::translate("MainWindow", "Trajectory Idle-Lifetime:", 0));
        label_48->setText(QApplication::translate("MainWindow", "Farneback Flow Minimum Motion:", 0));
        label_49->setText(QApplication::translate("MainWindow", "Linear Low-Pass Filter x-coord:", 0));
        label_50->setText(QApplication::translate("MainWindow", "Linear Low-Pass Filter y-coord:", 0));
        label_51->setText(QApplication::translate("MainWindow", "Lucas-Kanade Flow Minimum Motion:", 0));
        label_52->setText(QApplication::translate("MainWindow", "SOF Directed Relational Factor x-coord:", 0));
        label_53->setText(QApplication::translate("MainWindow", "SOF Directed Relational Factor y-coord:", 0));
        label_54->setText(QApplication::translate("MainWindow", "SOF Idle Trajectory Suppression Threshold Ticks:", 0));
        label_55->setText(QApplication::translate("MainWindow", "SOF Minimum Trajectory States:", 0));
        label_30->setText(QApplication::translate("MainWindow", " Dense Optical Flow", 0));
        label_31->setText(QApplication::translate("MainWindow", " Sparse Optical Flow", 0));
        radioButton_5->setText(QApplication::translate("MainWindow", "Dense (Farneback)", 0));
        radioButton_6->setText(QApplication::translate("MainWindow", "Sparse (Lucas-Kanade)", 0));
        label_32->setText(QApplication::translate("MainWindow", "Optical Flow:", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Optical Layer", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("MainWindow", "Dynamic Model", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("MainWindow", "Overlay", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "Memory Management", 0));
        menuFile->setTitle(QApplication::translate("MainWindow", "File", 0));
        menuView->setTitle(QApplication::translate("MainWindow", "View", 0));
        menuHelp->setTitle(QApplication::translate("MainWindow", "Help", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
