
#ifndef CONFIGS_H_
#define CONFIGS_H_

#define FRAME_HEIGHT					240
#define FRAME_WIDTH						320

// Fast memory configuration
#define FAST_MEM_POOL_FRAMES_MAX		20

//
// Data Association configuration
//
#define CFG_DATA_ASSOCIAT_SAMPLES_OFFSET					5.0
#define CFG_DATA_ASSOCIAT_TRAJ_CORRESP_PERCENT				0.8

//
// Stateful Object Filter configuration
//
#define CFG_STATEFUL_OBJ_FILTER_RELATED_MAX_DIFFX			30.0
#define CFG_STATEFUL_OBJ_FILTER_RELATED_MAX_DIFFY			30.0
#define CFG_STATEFUL_OBJ_FILTER_RELATED_MAX_DISPL_DIFFX		30.0
#define CFG_STATEFUL_OBJ_FILTER_RELATED_MAX_DISPL_DIFFY		30.0
#define CFG_STATEFUL_OBJ_FILTER_IDLE_MAX_TICKS				3
#define CFG_STATEFUL_OBJ_FILTER_TRAJ_STATES_MIN				3
#define CFG_PYRLK_MIN_DIST									0

//
// Global USE flags
//
//#define CFG_USE_GPU

//
// Dynamic Model 3D USE flags
//

#define CFG_3D_MODEL_USE_KALMAN_FILTER
//#define CFG_3D_MODEL_USE_GLOBAL_TRAJECTORY_Z_VARIABLE
#define CFG_3D_MODEL_FITTING_USE_TRUEOBJECT_ONLY
#define CFG_3D_MODEL_FITTING_TRAJECTORY_JUMP_NORM			999999//150
#define CFG_3D_MODEL_KF_MEM_SIZE					 		2000
#define KF_AXIS_ERR_SIGMA									60//40
#define KF_PROCESS_NOISE_COV								0.5
#define KF_INIT_VALUE_P										1.0

//
// Dynamic Model 3D switches and constants
//
#define CFG_3D_MODEL_OBJECT_CENTER_MONTECARLO_ITERAT			100
//#define CFG_3D_MODEL_ASSUMPTION_DEPTH_VELOCITY_MONOTONIC

//
// Dynamic Model 2D USE flags
//

//
// Optical Layer USE flags
//

//
// Optical Layer constants
//

#define CFG_OPTICAL_LAYER_OBJECT_ESTIMAT_MORPH_DILAT_KERNEL_SIZE	4
#define CFG_OPTICAL_LAYER_TRUEOBJECT_GRAYSCALE_THRESH		140
#define CFG_OPTICAL_LAYER_TRUEOBJECT_PIXEL_WIDTH_MIN		4
#define CFG_OPTICAL_LAYER_TRUEOBJECT_PIXEL_HEIGHT_MIN		4

#define CFG_OPTICAL_LAYER_TRUEOBJECT_ECCENTRICITY_EPS		0.2

#define CFG_OPTICAL_LAYER_OBJECT_ESTIMAT_MONTECARLO_ITERAT	1000
#define CFG_OPTICAL_LAYER_REGION_OVERLAP_PIXEL_TOLERANCE	4
#define CFG_OPTICAL_LAYER_OBJECT_ESTIMAT_OVERLAP_PIXEL_TOLERANCE	1
#define CFG_OPTICAL_LAYER_REGION_EXTENSION_RETRIES			5
#define CFG_OPTICAL_LAYER_CONTRAST_DILATE_RETRIES			3

#endif /* CONFIGS_H_ */
